### ISSUE TITLE
A Seeming Bug 

### ISSUE THREAD

**Issue by Tereams** [wzzzd/lm_ner#11]
![image](https://user-images.githubusercontent.com/106360504/193607601-46576084-9e59-4d6e-9cd0-ef262b500834.png)
i was wondering if there is a bug in the function BIMES2BIO( ) in eval.py as was circled in the picture  **:-)**
it **does** make some difference in the answers in my situation

**Comment by wzzzd** [comment]
Actually, it is a bug. You' re really careful! That can be replaced with `re.sub('S-',  'B-',  x)`

**Comment by wzzzd** [comment]
Actually, it is a bug. You' re really careful! 
It can be replaced with `re.sub('S-', 'B-', x)`
